[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Now"
  pageRef = "now"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40




